# Adapted from chromiumembedded/cef-project under its BSD-style license.
function(DownloadCEF platform channel version distribution_type download_dir)
  if(channel STREQUAL "beta")
    set(channel_part "_beta")
  else()
    set(channel_part "")
  endif()
  if(distribution_type STREQUAL "minimal")
    set(type_part "_minimal")
  else()
    set(type_part "")
  endif()

  set(CEF_DISTRIBUTION "cef_binary_${version}_${platform}${channel_part}${type_part}")
  set(CEF_DOWNLOAD_DIR "${download_dir}")
  set(CEF_ROOT "${CEF_DOWNLOAD_DIR}/${CEF_DISTRIBUTION}" CACHE INTERNAL "CEF_ROOT")

  if(NOT IS_DIRECTORY "${CEF_ROOT}")
    file(MAKE_DIRECTORY "${CEF_DOWNLOAD_DIR}")
    set(CEF_DOWNLOAD_FILENAME "${CEF_DISTRIBUTION}.tar.bz2")
    set(CEF_DOWNLOAD_PATH "${CEF_DOWNLOAD_DIR}/${CEF_DOWNLOAD_FILENAME}")
    if(NOT EXISTS "${CEF_DOWNLOAD_PATH}")
      set(CEF_DOWNLOAD_HOST "https:" "//cef-builds.spotifycdn.com")
      string(CONCAT CEF_DOWNLOAD_URL ${CEF_DOWNLOAD_HOST} "/" ${CEF_DOWNLOAD_FILENAME})
      string(REPLACE "+" "%2B" CEF_DOWNLOAD_URL_ESCAPED "${CEF_DOWNLOAD_URL}")
      message(STATUS "Downloading CEF checksum...")
      file(DOWNLOAD "${CEF_DOWNLOAD_URL_ESCAPED}.sha1" "${CEF_DOWNLOAD_PATH}.sha1"
           STATUS checksum_status TLS_VERIFY ON)
      list(GET checksum_status 0 checksum_code)
      if(NOT checksum_code EQUAL 0)
        message(FATAL_ERROR "Unable to download CEF checksum: ${checksum_status}")
      endif()
      file(READ "${CEF_DOWNLOAD_PATH}.sha1" CEF_SHA1)
      string(STRIP "${CEF_SHA1}" CEF_SHA1)
      message(STATUS "Downloading CEF ${version} for ${platform}...")
      file(DOWNLOAD "${CEF_DOWNLOAD_URL_ESCAPED}" "${CEF_DOWNLOAD_PATH}"
           EXPECTED_HASH SHA1=${CEF_SHA1} SHOW_PROGRESS STATUS download_status TLS_VERIFY ON)
      list(GET download_status 0 download_code)
      if(NOT download_code EQUAL 0)
        file(REMOVE "${CEF_DOWNLOAD_PATH}")
        message(FATAL_ERROR "Unable to download CEF: ${download_status}")
      endif()
    endif()
    message(STATUS "Extracting ${CEF_DOWNLOAD_FILENAME}...")
    execute_process(COMMAND ${CMAKE_COMMAND} -E tar xzf "${CEF_DOWNLOAD_PATH}"
                    WORKING_DIRECTORY "${CEF_DOWNLOAD_DIR}"
                    RESULT_VARIABLE extract_result)
    if(NOT extract_result EQUAL 0 OR NOT IS_DIRECTORY "${CEF_ROOT}")
      message(FATAL_ERROR "CEF extraction failed with code ${extract_result}")
    endif()
  endif()
endfunction()
