name: Core CI
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake -S . -B out/build -DBRAVELIKE_BUILD_TESTS=ON
      - name: Build
        run: cmake --build out/build --config Release
      - name: Test
        run: ctest --test-dir out/build -C Release --output-on-failure
